name: infrastructure-prod

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/infrastructure.yml'
      - '.github/workflows/infrastructure-prod.yml'
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  infrastructure-prod:
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: prod
      proxyAddress: ${{ vars.PROXY_ADDRESS }}
      disallowedUserAgents: ${{ vars.DISALLOWED_USER_AGENTS }}
      existing: true
    secrets: 
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      apiKey: ${{ secrets.API_KEY }}
      proxyUserName: ${{ secrets.PROXY_USERNAME }}
      proxyPassword: ${{ secrets.PROXY_PASSWORD }}