name: infrastructure-dev

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/infrastructure.yml'
      - '.github/workflows/infrastructure-dev.yml'
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  infrastructure-dev:
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: staging
      proxyAddress: ${{ vars.PROXY_ADDRESS }}
      disallowedUserAgents: ${{ vars.DISALLOWED_USER_AGENTS }}
      existing: true
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      apiKey: ${{ secrets.API_KEY_STAGING }}
      proxyUserName: ${{ secrets.PROXY_USERNAME }}
      proxyPassword: ${{ secrets.PROXY_PASSWORD }}